name: CI
#control workflow when will run
on:
push:
  branches: [ main ]

pull_request:
  branches: [ main ]


workflow_dispatch:

jobs:
build:
runs-on: windows-latest

steps:
- name: actions/checkout@v3
- name: run a multi-line script
run:
echo Add other actions to build,
echo test,and deploy your project.
